version: "3.6"
services:
  rabbitmq:
    #container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    
  apigateway:
    container_name: apigateway-container
    image: apigateway.api  
    restart: on-failure        

  identityapi:
    #container_name: identityapi-container
    image: identity.api
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    restart: on-failure        
    depends_on:
        - sqldata
        - rabbitmq
    links: 
      - rabbitmq

  hotelapi:
    #container_name: hotelapi-container
    image: hotel.api
    build:
      context: .
      dockerfile: Services/Hotel/Hotel.API/Dockerfile
    restart: on-failure        
    depends_on:
        - sqldata

  bookingapi:
    #container_name: bookingapi-container
    image: booking.api
    build:
      context: .
      dockerfile: Services/Booking/Booking.API/Dockerfile
    restart: on-failure    
    depends_on:
      - sqldata
      - rabbitmq
    links: 
      - rabbitmq
      
  webmvc:
    #container_name: webmvc-container
    image: webmvc 
    restart: on-failure
    
  webspa:
    image: webspa
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
    restart: on-failure
  
  sqldata:
    container_name: sqldata-container
    image:
      "mcr.microsoft.com/mssql/server"
    restart: on-failure     
