version: "3.6"
services:
  rabbitmq:
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password        
    image: rabbitmq:3-management
    
  apigateway:
    container_name: apigateway-container
    image: apigateway.api  
    ports:
        - 8000:80
        - 8001:443    
    restart: on-failure        

  identityapi:
    container_name: identityapi-container
    image: identity.api
    environment:
      - ConnectionString=Server=sqldata;Initial Catalog=IdentityAPI;User Id=sa;Password=iamback.786A@
    ports:
        - 6000:80
        - 6001:443    
    restart: on-failure        
    depends_on:
        - sqldata
        - rabbitmq

  hotelapi:
    container_name: hotelapi-container
    image: hotel.api  
    environment:
      - ConnectionString=Server=sqldata;Initial Catalog=HotelAPI;User Id=sa;Password=iamback.786A@
    ports:
        - 7000:80
        - 7001:443    
    
    restart: on-failure        
    depends_on:
        - sqldata

  bookingapi:
    container_name: bookingapi-container
    image: booking.api  
    environment:
      - ConnectionString=Server=sqldata;Initial Catalog=BookingAPI;User Id=sa;Password=iamback.786A@
    ports:
        - 9000:80
        - 9001:443    
    
    restart: on-failure        
    depends_on:
        - sqldata
  
  sqldata:
    container_name: sqldata-container
    image:
      "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=iamback.786A@
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - sqlvolumehotelmanagementsystem:/var/opt/mssql
    restart: on-failure     

volumes:
  sqlvolumehotelmanagementsystem: